## NumPy

In [1]:
import numpy as np

### numpy 2D array (number of rows x number of columns)

#### np.zeros

In [23]:
array1 = np.zeros((4,3))
print(array1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
print(array1.dtype)

float64


#### np.ones

In [25]:
array2 = np.ones((3,3))
print(array2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
print(array2.shape)

(3, 3)


#### np.random.rand

In [31]:
array3 = np.random.rand(5,6)
print(array3)

[[0.72303563 0.52827637 0.65134276 0.31116032 0.36390863 0.10367427]
 [0.81060824 0.77565929 0.54647903 0.02202864 0.54288516 0.81493375]
 [0.59136031 0.10504514 0.70056736 0.39879714 0.8120675  0.7204071 ]
 [0.36303931 0.88434359 0.56014197 0.62197464 0.37559281 0.81489665]
 [0.76958594 0.52903563 0.8322792  0.59224767 0.80088938 0.40214045]]


In [28]:
print('Number of rows in array3 = {}'.format(array3.shape[0]))
print('Number of columns in array3 = {}'.format(array3.shape[1]))

Number of rows in array3 = 5
Number of columns in array3 = 6


#### uint8 data type

In [30]:
array4 = np.zeros((4,2), dtype=np.uint8)
print(array4)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [32]:
print(array4.dtype)

uint8


#### array 5x6 with values from 1 to 30

In [33]:
array5 = np.array([[1,2,3,4,5,6],
                  [7,8,9,10,11,12],
                  [13,14,15,16,17,18],
                  [19,20,21,22,23,24],
                  [25,26,27,28,29,30]],
                  dtype=np.uint8)

In [35]:
print(array5)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
